baseURL = "/"
languageCode = "es-es"
title = "Villa de Tejado"
themesDir = "themes"
theme = "hero-tejado"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Tejado (Soria)"
    meta_og_title = "Villa de Tejado"
    meta_og_type = "website"
    meta_og_url = "https://villadetejado.es"
    meta_og_image = "https://raw.githubusercontent.com/rsciriano/villadetejado.es/main/static/images/tejado_aerea.jpg"
    meta_og_description = "Tejado (Soria)"
    #meta_twitter_card = "summary"
    #meta_twitter_site = "@zerostaticio"
    #meta_twitter_creator = "@zerostaticio"


[[menu.main]]
    name = "Situación geográfica"
    url = "/situacion-geografica/"
    weight = 1

[[menu.main]]
    name = "Historia"
    url = "/historia/"
    weight = 2

[[menu.main]]
    name = "Lugares de interés"
    url = "/lugares-de-interes/"
    weight = 3

[[menu.main]]
    name = "Rutas en bici"
    url = "/rutas-bici/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
